spring:
  application:
    name: kafka-stream-java

kafka:
  streams:
    applicationIdConfig: kafka-stream-java
    bootstrapServersConfig: localhost:9092
    topics:
      input: sandbox
      output: sandbox-out